In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

## Tensor

In [3]:
tensor = torch.Tensor(2, 3)

In [5]:
print(tensor)
print(f'Shape: {tensor.shape}, Dtype: {tensor.dtype}')

tensor([[1.8639e-02, 4.5698e-41, 1.7346e+16],
        [3.0722e-41, 1.7346e+16, 3.0722e-41]])
Shape: torch.Size([2, 3]), Dtype: torch.float32


In [6]:
tensor = torch.empty((1, 4), dtype=torch.float64)

In [7]:
print(tensor)
print(f'Shape: {tensor.shape}, Dtype: {tensor.dtype}')

tensor([[6.9201e-310, 4.6523e-310, 1.5810e-322, 3.1620e-322]],
       dtype=torch.float64)
Shape: torch.Size([1, 4]), Dtype: torch.float64


In [8]:
tensor = torch.zeros((3, 2), dtype=torch.int)

In [9]:
print(tensor)
print(f'Shape: {tensor.shape}, Dtype: {tensor.dtype}')

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)
Shape: torch.Size([3, 2]), Dtype: torch.int32


In [10]:
tensor = torch.ones((3, 1), dtype=torch.bool)

In [11]:
print(tensor)
print(f'Shape: {tensor.shape}, Dtype: {tensor.dtype}')

tensor([[True],
        [True],
        [True]])
Shape: torch.Size([3, 1]), Dtype: torch.bool


In [19]:
tensor = torch.zeros((1000, 1000, 1000), dtype=torch.float64, device='cuda')

In [21]:
tensor = tensor.to('cpu')

In [24]:
torch.cuda.empty_cache()

In [25]:
!nvidia-smi

Thu Feb 20 06:36:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:3D:00.0 Off |                  N/A |
| 23%   29C    P2    68W / 250W |    529MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:3E:00.0 Off |                  N/A |
| 32%   55C    P2   110W / 250W |  12143MiB / 12196MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   2  T

## Module

In [28]:
model = torch.nn.Sequential(
    torch.nn.Conv2d(1, 16, kernel_size=3),
    torch.nn.Conv2d(16, 32, kernel_size=5),
    torch.nn.Conv2d(32, 64, kernel_size=7),
)

In [29]:
inputs = torch.zeros((1, 1, 28, 28))

In [42]:
output = model(inputs)

In [32]:
output.shape

torch.Size([1, 64, 16, 16])

In [43]:
result = output.mean()

In [44]:
result.backward()

In [81]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.fc1 = nn.Linear(28*28*1, 10)
        self.fc2 = nn.Linear(28*28*1, 10)
        self.fc3 = nn.Linear(28*28*1, 10)
        self.fc4 = nn.Linear(28*28*1, 10)
        self.fc5 = nn.Linear(28*28*1, 10)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.fc(x.view(-1, 28*28*1))
        return x

In [82]:
model = Network()

In [52]:
output = model(inputs)

In [53]:
output

tensor([[-0.0143, -0.0087, -0.0008, -0.0027, -0.0124, -0.0273,  0.0112,  0.0317,
         -0.0295,  0.0187]], grad_fn=<AddmmBackward>)

In [72]:
result = output.mean()

In [75]:
result.backward()

In [83]:
model.state_dict().keys()

odict_keys(['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias', 'fc4.weight', 'fc4.bias', 'fc5.weight', 'fc5.bias'])

In [ ]:
model.state_dict().keys()

In [84]:
torch.save(model.state_dict(), 'model.pt')

In [85]:
model = torch.load('model.pt')