# Deep Learning basic (PyTorch)

- **Instructor**: Jongwoo Lim / Jiun Bae
- **Email**: [jlim@hanyang.ac.kr](mailto:jlim@hanyang.ac.kr) / [jiunbae.623@gmail.com](mailto:jiunbae.623@gmail.com)

## Pytorch Example

In this example you will practice a basic uage of [PyTorch](https://pytorch.org). The goals of this example are as follows:

- Learn basically how to **write and use code**(*PyTorch*).

The [Python](https://www.python.org) is a programming language that lets you work quickly and integrate systems more effectively. It is widely used in various fields, and also used in machine learning.

*If you are more familiar with TensorFlow(or Keras), We'll see if We can help you in other ways. But PyTorch is still a good choice for beginners(or expert also).*

And this example also is written in [IPython Notebook](https://ipython.org/notebook.html), an interactive computational environment, in which you can run code directly.

In [8]:
import torch
import numpy as np

## Tensor

In [5]:
# not initialized tensor
x = torch.Tensor(5, 3)
print(x)
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 6.2121e+22, 1.8788e+31],
        [1.7220e+22, 3.8678e-05, 1.0432e+21],
        [1.0470e-11, 2.6513e-09, 4.1540e+21],
        [6.7054e+22, 2.6081e+20, 1.3401e-08],
        [2.1781e-04, 3.1369e+27, 7.0800e+31]])
tensor([[-1.0066e+09,  4.5846e-41, -1.0066e+09],
        [ 4.5846e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00,  1.2692e-25],
        [ 3.0680e-41,  1.3563e-19,  1.3563e-19],
        [ 2.6865e+09,  4.5439e+30,  7.1843e+22]])


In [7]:
# random initialized tensor
x = torch.rand(5, 3)
print(x)
# zero-filled tensor
x = torch.zeros(5, 3)
print(x)

tensor([[0.6446, 0.7425, 0.4622],
        [0.7844, 0.1499, 0.7691],
        [0.0280, 0.7606, 0.1887],
        [0.5142, 0.4939, 0.8363],
        [0.4492, 0.5305, 0.3743]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# tensor from python or numpy array
x = torch.Tensor([3, 2, 1])
print(x)
x = torch.Tensor(np.array([[3, 2, 1], [1, 2, 3]]))
print(x)

tensor([3., 2., 1.])
tensor([[3., 2., 1.],
        [1., 2., 3.]])


In [13]:
print(x.size())
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


## Operation

In [17]:
x = torch.zeros(3, 3)
y = torch.ones(3, 3)
print(x, '\n', y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [18]:
print(x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# in-place operation ends with '_'
x.add_(y)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Indexing

In [23]:
x = torch.rand(4, 3, 2)
print(x, x.shape)

tensor([[[0.5733, 0.2288],
         [0.3601, 0.0502],
         [0.7972, 0.0282]],

        [[0.0221, 0.9839],
         [0.5379, 0.6878],
         [0.4216, 0.0333]],

        [[0.9589, 0.0035],
         [0.9263, 0.1372],
         [0.5770, 0.5142]],

        [[0.2999, 0.3636],
         [0.6559, 0.7690],
         [0.9739, 0.3121]]]) torch.Size([4, 3, 2])


In [25]:
print(x[0, 0, 0])

tensor(0.5733)


In [26]:
print(x[0, 0])

tensor([0.5733, 0.2288])


In [27]:
print(x[0])

tensor([[0.5733, 0.2288],
        [0.3601, 0.0502],
        [0.7972, 0.0282]])


In [28]:
print(x[:, 0, :])

tensor([[0.5733, 0.2288],
        [0.0221, 0.9839],
        [0.9589, 0.0035],
        [0.2999, 0.3636]])


In [30]:
print(x[:, 1, 1])

tensor([0.0502, 0.6878, 0.1372, 0.7690])


In [32]:
print(x.shape)
print(x.view(2,3,4).shape)
print(x.reshape(-1, 3).shape)

torch.Size([4, 3, 2])
torch.Size([2, 3, 4])
torch.Size([8, 3])


## to numpy

In [43]:
ary = np.random.rand(6, 2, 4)

In [51]:
x = torch.Tensor(ary)

In [50]:
np.all(x.numpy() == ary)

False

## to device

In [56]:
device_cpu = torch.device('cpu')
device_gpu = torch.device('cuda')

In [57]:
x = torch.empty(3, 2)

In [58]:
print(x.device)

cpu


In [60]:
x.to(device_gpu)
print(x.device)

AssertionError: Torch not compiled with CUDA enabled